/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Language from './Language';

/**
 * The ActivateAccountRequest model module.
 * @module model/ActivateAccountRequest
 * @version 4.3.2
 */
class ActivateAccountRequest {
    /**
     * Constructs a new <code>ActivateAccountRequest</code>.
     * @alias module:model/ActivateAccountRequest
     * @param activationToken {String} 
     * @param password {String} 
     * @param firstName {String} 
     * @param lastName {String} 
     * @param language {module:model/Language} 
     */
    constructor(activationToken, password, firstName, lastName, language) { 
        
        ActivateAccountRequest.initialize(this, activationToken, password, firstName, lastName, language);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, activationToken, password, firstName, lastName, language) { 
        obj['activation_token'] = activationToken;
        obj['password'] = password;
        obj['first_name'] = firstName;
        obj['last_name'] = lastName;
        obj['language'] = language;
    }

    /**
     * Constructs a <code>ActivateAccountRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ActivateAccountRequest} obj Optional instance to populate.
     * @return {module:model/ActivateAccountRequest} The populated <code>ActivateAccountRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ActivateAccountRequest();

            if (data.hasOwnProperty('activation_token')) {
                obj['activation_token'] = ApiClient.convertToType(data['activation_token'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = Language.constructFromObject(data['language']);
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('eula_version')) {
                obj['eula_version'] = ApiClient.convertToType(data['eula_version'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} activation_token
 */
ActivateAccountRequest.prototype['activation_token'] = undefined;

/**
 * @member {String} password
 */
ActivateAccountRequest.prototype['password'] = undefined;

/**
 * @member {String} first_name
 */
ActivateAccountRequest.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
ActivateAccountRequest.prototype['last_name'] = undefined;

/**
 * @member {module:model/Language} language
 */
ActivateAccountRequest.prototype['language'] = undefined;

/**
 * @member {String} phone
 */
ActivateAccountRequest.prototype['phone'] = undefined;

/**
 * @member {String} eula_version
 */
ActivateAccountRequest.prototype['eula_version'] = undefined;






export default ActivateAccountRequest;

