/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AddFieldsRequest model module.
 * @module model/AddFieldsRequest
 * @version 4.3.2
 */
class AddFieldsRequest {
    /**
     * Constructs a new <code>AddFieldsRequest</code>.
     * @alias module:model/AddFieldsRequest
     * @param locationID {String} 
     * @param gdpVehicle {Boolean} 
     * @param _date {String} 
     * @param dayTemp {Number} 
     */
    constructor(locationID, gdpVehicle, _date, dayTemp) { 
        
        AddFieldsRequest.initialize(this, locationID, gdpVehicle, _date, dayTemp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, locationID, gdpVehicle, _date, dayTemp) { 
        obj['locationID'] = locationID;
        obj['gdpVehicle'] = gdpVehicle;
        obj['date'] = _date;
        obj['dayTemp'] = dayTemp;
    }

    /**
     * Constructs a <code>AddFieldsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddFieldsRequest} obj Optional instance to populate.
     * @return {module:model/AddFieldsRequest} The populated <code>AddFieldsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddFieldsRequest();

            if (data.hasOwnProperty('locationID')) {
                obj['locationID'] = ApiClient.convertToType(data['locationID'], 'String');
            }
            if (data.hasOwnProperty('gdpVehicle')) {
                obj['gdpVehicle'] = ApiClient.convertToType(data['gdpVehicle'], 'Boolean');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('dayTemp')) {
                obj['dayTemp'] = ApiClient.convertToType(data['dayTemp'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} locationID
 */
AddFieldsRequest.prototype['locationID'] = undefined;

/**
 * @member {Boolean} gdpVehicle
 */
AddFieldsRequest.prototype['gdpVehicle'] = undefined;

/**
 * @member {String} date
 */
AddFieldsRequest.prototype['date'] = undefined;

/**
 * @member {Number} dayTemp
 */
AddFieldsRequest.prototype['dayTemp'] = undefined;






export default AddFieldsRequest;

