/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangeRoleOfUserRequest model module.
 * @module model/ChangeRoleOfUserRequest
 * @version 4.3.2
 */
class ChangeRoleOfUserRequest {
    /**
     * Constructs a new <code>ChangeRoleOfUserRequest</code>.
     * @alias module:model/ChangeRoleOfUserRequest
     * @param roleId {String} 
     */
    constructor(roleId) { 
        
        ChangeRoleOfUserRequest.initialize(this, roleId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, roleId) { 
        obj['role_id'] = roleId;
    }

    /**
     * Constructs a <code>ChangeRoleOfUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeRoleOfUserRequest} obj Optional instance to populate.
     * @return {module:model/ChangeRoleOfUserRequest} The populated <code>ChangeRoleOfUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeRoleOfUserRequest();

            if (data.hasOwnProperty('role_id')) {
                obj['role_id'] = ApiClient.convertToType(data['role_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} role_id
 */
ChangeRoleOfUserRequest.prototype['role_id'] = undefined;






export default ChangeRoleOfUserRequest;

