/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangePasswordRequest model module.
 * @module model/ChangePasswordRequest
 * @version 4.3.2
 */
class ChangePasswordRequest {
    /**
     * Constructs a new <code>ChangePasswordRequest</code>.
     * @alias module:model/ChangePasswordRequest
     */
    constructor() { 
        
        ChangePasswordRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChangePasswordRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangePasswordRequest} obj Optional instance to populate.
     * @return {module:model/ChangePasswordRequest} The populated <code>ChangePasswordRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangePasswordRequest();

            if (data.hasOwnProperty('current_password')) {
                obj['current_password'] = ApiClient.convertToType(data['current_password'], 'String');
            }
            if (data.hasOwnProperty('new_password')) {
                obj['new_password'] = ApiClient.convertToType(data['new_password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} current_password
 */
ChangePasswordRequest.prototype['current_password'] = undefined;

/**
 * @member {String} new_password
 */
ChangePasswordRequest.prototype['new_password'] = undefined;






export default ChangePasswordRequest;

