/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ComplianceReason model module.
 * @module model/ComplianceReason
 * @version 4.3.2
 */
class ComplianceReason {
    /**
     * Constructs a new <code>ComplianceReason</code>.
     * @alias module:model/ComplianceReason
     * @param name {String} 
     * @param active {Boolean} 
     */
    constructor(name, active) { 
        
        ComplianceReason.initialize(this, name, active);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, active) { 
        obj['name'] = name;
        obj['active'] = active;
    }

    /**
     * Constructs a <code>ComplianceReason</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComplianceReason} obj Optional instance to populate.
     * @return {module:model/ComplianceReason} The populated <code>ComplianceReason</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComplianceReason();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
ComplianceReason.prototype['id'] = undefined;

/**
 * @member {Date} created_at
 */
ComplianceReason.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
ComplianceReason.prototype['updated_at'] = undefined;

/**
 * @member {String} name
 */
ComplianceReason.prototype['name'] = undefined;

/**
 * @member {Boolean} active
 */
ComplianceReason.prototype['active'] = undefined;






export default ComplianceReason;

