/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateFieldRequest model module.
 * @module model/CreateFieldRequest
 * @version 4.3.2
 */
class CreateFieldRequest {
    /**
     * Constructs a new <code>CreateFieldRequest</code>.
     * @alias module:model/CreateFieldRequest
     * @param identifier {String} 
     * @param type {String} 
     * @param name {String} 
     * @param required {Boolean} 
     * @param showInTemperatureGraph {Boolean} 
     */
    constructor(identifier, type, name, required, showInTemperatureGraph) { 
        
        CreateFieldRequest.initialize(this, identifier, type, name, required, showInTemperatureGraph);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, identifier, type, name, required, showInTemperatureGraph) { 
        obj['identifier'] = identifier;
        obj['type'] = type;
        obj['name'] = name;
        obj['required'] = required;
        obj['show_in_temperature_graph'] = showInTemperatureGraph;
    }

    /**
     * Constructs a <code>CreateFieldRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateFieldRequest} obj Optional instance to populate.
     * @return {module:model/CreateFieldRequest} The populated <code>CreateFieldRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateFieldRequest();

            if (data.hasOwnProperty('identifier')) {
                obj['identifier'] = ApiClient.convertToType(data['identifier'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
            if (data.hasOwnProperty('show_in_temperature_graph')) {
                obj['show_in_temperature_graph'] = ApiClient.convertToType(data['show_in_temperature_graph'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} identifier
 */
CreateFieldRequest.prototype['identifier'] = undefined;

/**
 * @member {String} type
 */
CreateFieldRequest.prototype['type'] = undefined;

/**
 * @member {String} name
 */
CreateFieldRequest.prototype['name'] = undefined;

/**
 * @member {Boolean} required
 */
CreateFieldRequest.prototype['required'] = undefined;

/**
 * @member {Boolean} show_in_temperature_graph
 */
CreateFieldRequest.prototype['show_in_temperature_graph'] = undefined;






export default CreateFieldRequest;

