/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GatewayInstallation model module.
 * @module model/GatewayInstallation
 * @version 4.3.2
 */
class GatewayInstallation {
    /**
     * Constructs a new <code>GatewayInstallation</code>.
     * @alias module:model/GatewayInstallation
     */
    constructor() { 
        
        GatewayInstallation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GatewayInstallation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GatewayInstallation} obj Optional instance to populate.
     * @return {module:model/GatewayInstallation} The populated <code>GatewayInstallation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GatewayInstallation();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('deleted_at')) {
                obj['deleted_at'] = ApiClient.convertToType(data['deleted_at'], 'Date');
            }
            if (data.hasOwnProperty('last_seen')) {
                obj['last_seen'] = ApiClient.convertToType(data['last_seen'], 'Date');
            }
            if (data.hasOwnProperty('company_id')) {
                obj['company_id'] = ApiClient.convertToType(data['company_id'], 'String');
            }
            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('heartbeat_data')) {
                obj['heartbeat_data'] = ApiClient.convertToType(data['heartbeat_data'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
GatewayInstallation.prototype['id'] = undefined;

/**
 * @member {String} name
 */
GatewayInstallation.prototype['name'] = undefined;

/**
 * @member {String} client_id
 */
GatewayInstallation.prototype['client_id'] = undefined;

/**
 * @member {Date} created_at
 */
GatewayInstallation.prototype['created_at'] = undefined;

/**
 * @member {Date} deleted_at
 */
GatewayInstallation.prototype['deleted_at'] = undefined;

/**
 * @member {Date} last_seen
 */
GatewayInstallation.prototype['last_seen'] = undefined;

/**
 * @member {String} company_id
 */
GatewayInstallation.prototype['company_id'] = undefined;

/**
 * @member {String} company_name
 */
GatewayInstallation.prototype['company_name'] = undefined;

/**
 * @member {Object} heartbeat_data
 */
GatewayInstallation.prototype['heartbeat_data'] = undefined;






export default GatewayInstallation;

