/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse400 model module.
 * @module model/InlineResponse400
 * @version 4.3.2
 */
class InlineResponse400 {
    /**
     * Constructs a new <code>InlineResponse400</code>.
     * @alias module:model/InlineResponse400
     */
    constructor() { 
        
        InlineResponse400.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse400</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse400} obj Optional instance to populate.
     * @return {module:model/InlineResponse400} The populated <code>InlineResponse400</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse400();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse400.StatusEnum} status
 */
InlineResponse400.prototype['status'] = undefined;

/**
 * @member {module:model/InlineResponse400.MessageEnum} message
 */
InlineResponse400.prototype['message'] = undefined;

/**
 * @member {module:model/InlineResponse400.ErrorEnum} error
 */
InlineResponse400.prototype['error'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {Number}
 * @readonly
 */
InlineResponse400['StatusEnum'] = {

    /**
     * value: 400
     * @const
     */
    "400": 400
};


/**
 * Allowed values for the <code>message</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse400['MessageEnum'] = {

    /**
     * value: "Invalid request"
     * @const
     */
    "Invalid request": "Invalid request"
};


/**
 * Allowed values for the <code>error</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse400['ErrorEnum'] = {

    /**
     * value: "one_admin_required"
     * @const
     */
    "one_admin_required": "one_admin_required"
};



export default InlineResponse400;

