/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse404 model module.
 * @module model/InlineResponse404
 * @version 4.3.2
 */
class InlineResponse404 {
    /**
     * Constructs a new <code>InlineResponse404</code>.
     * @alias module:model/InlineResponse404
     */
    constructor() { 
        
        InlineResponse404.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse404</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse404} obj Optional instance to populate.
     * @return {module:model/InlineResponse404} The populated <code>InlineResponse404</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse404();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse404.StatusEnum} status
 */
InlineResponse404.prototype['status'] = undefined;

/**
 * @member {module:model/InlineResponse404.MessageEnum} message
 */
InlineResponse404.prototype['message'] = undefined;

/**
 * @member {module:model/InlineResponse404.ErrorEnum} error
 */
InlineResponse404.prototype['error'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {Number}
 * @readonly
 */
InlineResponse404['StatusEnum'] = {

    /**
     * value: 404
     * @const
     */
    "404": 404
};


/**
 * Allowed values for the <code>message</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse404['MessageEnum'] = {

    /**
     * value: "Not found"
     * @const
     */
    "Not found": "Not found"
};


/**
 * Allowed values for the <code>error</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse404['ErrorEnum'] = {

    /**
     * value: "user_not_found"
     * @const
     */
    "user_not_found": "user_not_found",

    /**
     * value: "role_not_found"
     * @const
     */
    "role_not_found": "role_not_found"
};



export default InlineResponse404;

