/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse200 model module.
 * @module model/InlineResponse200
 * @version 4.3.2
 */
class InlineResponse200 {
    /**
     * Constructs a new <code>InlineResponse200</code>.
     * @alias module:model/InlineResponse200
     */
    constructor() { 
        
        InlineResponse200.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse200} obj Optional instance to populate.
     * @return {module:model/InlineResponse200} The populated <code>InlineResponse200</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200();

            if (data.hasOwnProperty('nonce_prefix')) {
                obj['nonce_prefix'] = ApiClient.convertToType(data['nonce_prefix'], 'String');
            }
            if (data.hasOwnProperty('mac_address')) {
                obj['mac_address'] = ApiClient.convertToType(data['mac_address'], 'String');
            }
            if (data.hasOwnProperty('next_index')) {
                obj['next_index'] = ApiClient.convertToType(data['next_index'], 'Number');
            }
            if (data.hasOwnProperty('next_timestamp')) {
                obj['next_timestamp'] = ApiClient.convertToType(data['next_timestamp'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} nonce_prefix
 */
InlineResponse200.prototype['nonce_prefix'] = undefined;

/**
 * @member {String} mac_address
 */
InlineResponse200.prototype['mac_address'] = undefined;

/**
 * @member {Number} next_index
 */
InlineResponse200.prototype['next_index'] = undefined;

/**
 * @member {Date} next_timestamp
 */
InlineResponse200.prototype['next_timestamp'] = undefined;

/**
 * @member {module:model/InlineResponse200.StatusEnum} status
 */
InlineResponse200.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse200['StatusEnum'] = {

    /**
     * value: "ok"
     * @const
     */
    "ok": "ok",

    /**
     * value: "already stopped"
     * @const
     */
    "already stopped": "already stopped"
};



export default InlineResponse200;

