/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InviteUserRequest model module.
 * @module model/InviteUserRequest
 * @version 4.3.2
 */
class InviteUserRequest {
    /**
     * Constructs a new <code>InviteUserRequest</code>.
     * @alias module:model/InviteUserRequest
     * @param email {String} 
     * @param roleId {String} 
     */
    constructor(email, roleId) { 
        
        InviteUserRequest.initialize(this, email, roleId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, email, roleId) { 
        obj['email'] = email;
        obj['role_id'] = roleId;
    }

    /**
     * Constructs a <code>InviteUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InviteUserRequest} obj Optional instance to populate.
     * @return {module:model/InviteUserRequest} The populated <code>InviteUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InviteUserRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('role_id')) {
                obj['role_id'] = ApiClient.convertToType(data['role_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} email
 */
InviteUserRequest.prototype['email'] = undefined;

/**
 * @member {String} first_name
 */
InviteUserRequest.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
InviteUserRequest.prototype['last_name'] = undefined;

/**
 * @member {String} role_id
 */
InviteUserRequest.prototype['role_id'] = undefined;






export default InviteUserRequest;

