/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Language.
* @enum {}
* @readonly
*/
export default class Language {
    
        /**
         * value: "de"
         * @const
         */
        "de" = "de";

    
        /**
         * value: "en"
         * @const
         */
        "en" = "en";

    

    /**
    * Returns a <code>Language</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Language} The enum <code>Language</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

