/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NotificationRequest model module.
 * @module model/NotificationRequest
 * @version 4.3.2
 */
class NotificationRequest {
    /**
     * Constructs a new <code>NotificationRequest</code>.
     * @alias module:model/NotificationRequest
     * @param recipientId {String} 
     * @param profileGroupId {String} 
     */
    constructor(recipientId, profileGroupId) { 
        
        NotificationRequest.initialize(this, recipientId, profileGroupId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, recipientId, profileGroupId) { 
        obj['recipient_id'] = recipientId;
        obj['profile_group_id'] = profileGroupId;
    }

    /**
     * Constructs a <code>NotificationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NotificationRequest} obj Optional instance to populate.
     * @return {module:model/NotificationRequest} The populated <code>NotificationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotificationRequest();

            if (data.hasOwnProperty('recipient_id')) {
                obj['recipient_id'] = ApiClient.convertToType(data['recipient_id'], 'String');
            }
            if (data.hasOwnProperty('profile_group_id')) {
                obj['profile_group_id'] = ApiClient.convertToType(data['profile_group_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} recipient_id
 */
NotificationRequest.prototype['recipient_id'] = undefined;

/**
 * @member {String} profile_group_id
 */
NotificationRequest.prototype['profile_group_id'] = undefined;






export default NotificationRequest;

