/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Permission.
* @enum {}
* @readonly
*/
export default class Permission {
    
        /**
         * value: "START_LOGGER"
         * @const
         */
        "START_LOGGER" = "START_LOGGER";

    
        /**
         * value: "READOUT_LOGGER"
         * @const
         */
        "READOUT_LOGGER" = "READOUT_LOGGER";

    
        /**
         * value: "LIST_SHIPMENTS"
         * @const
         */
        "LIST_SHIPMENTS" = "LIST_SHIPMENTS";

    
        /**
         * value: "LIST_RECEIVED_SHIPMENTS"
         * @const
         */
        "LIST_RECEIVED_SHIPMENTS" = "LIST_RECEIVED_SHIPMENTS";

    
        /**
         * value: "ADD_COMMENTS"
         * @const
         */
        "ADD_COMMENTS" = "ADD_COMMENTS";

    
        /**
         * value: "ADMINISTRATE_COMPANY"
         * @const
         */
        "ADMINISTRATE_COMPANY" = "ADMINISTRATE_COMPANY";

    
        /**
         * value: "HANDLE_SHIPMENT"
         * @const
         */
        "HANDLE_SHIPMENT" = "HANDLE_SHIPMENT";

    
        /**
         * value: "CREATE_SHIPMENT_PROFILES"
         * @const
         */
        "CREATE_SHIPMENT_PROFILES" = "CREATE_SHIPMENT_PROFILES";

    
        /**
         * value: "admin:all"
         * @const
         */
        "admin:all" = "admin:all";

    

    /**
    * Returns a <code>Permission</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Permission} The enum <code>Permission</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

