/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SetCompliantRequest model module.
 * @module model/SetCompliantRequest
 * @version 4.3.2
 */
class SetCompliantRequest {
    /**
     * Constructs a new <code>SetCompliantRequest</code>.
     * @alias module:model/SetCompliantRequest
     * @param comment {String} 
     */
    constructor(comment) { 
        
        SetCompliantRequest.initialize(this, comment);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, comment) { 
        obj['comment'] = comment;
    }

    /**
     * Constructs a <code>SetCompliantRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetCompliantRequest} obj Optional instance to populate.
     * @return {module:model/SetCompliantRequest} The populated <code>SetCompliantRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetCompliantRequest();

            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} comment
 */
SetCompliantRequest.prototype['comment'] = undefined;






export default SetCompliantRequest;

