/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ShipmentsShipmentIdEventsNotifications model module.
 * @module model/ShipmentsShipmentIdEventsNotifications
 * @version 4.3.2
 */
class ShipmentsShipmentIdEventsNotifications {
    /**
     * Constructs a new <code>ShipmentsShipmentIdEventsNotifications</code>.
     * @alias module:model/ShipmentsShipmentIdEventsNotifications
     * @param userId {String} 
     */
    constructor(userId) { 
        
        ShipmentsShipmentIdEventsNotifications.initialize(this, userId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userId) { 
        obj['user_id'] = userId;
    }

    /**
     * Constructs a <code>ShipmentsShipmentIdEventsNotifications</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ShipmentsShipmentIdEventsNotifications} obj Optional instance to populate.
     * @return {module:model/ShipmentsShipmentIdEventsNotifications} The populated <code>ShipmentsShipmentIdEventsNotifications</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ShipmentsShipmentIdEventsNotifications();

            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
            }
            if (data.hasOwnProperty('user_name')) {
                obj['user_name'] = ApiClient.convertToType(data['user_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} user_id
 */
ShipmentsShipmentIdEventsNotifications.prototype['user_id'] = undefined;

/**
 * @member {String} user_name
 */
ShipmentsShipmentIdEventsNotifications.prototype['user_name'] = undefined;






export default ShipmentsShipmentIdEventsNotifications;

