/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StartShipmentRequest model module.
 * @module model/StartShipmentRequest
 * @version 4.3.2
 */
class StartShipmentRequest {
    /**
     * Constructs a new <code>StartShipmentRequest</code>.
     * @alias module:model/StartShipmentRequest
     * @param trackingId {String} 
     * @param startTimestamp {String} 
     * @param commissioningTime {String} 
     * @param shipmentProfileId {String} 
     * @param nonce {String} 
     * @param macAddress {String} 
     * @param firmwareVersionMajor {Number} 
     * @param firmwareVersionMinor {Number} 
     */
    constructor(trackingId, startTimestamp, commissioningTime, shipmentProfileId, nonce, macAddress, firmwareVersionMajor, firmwareVersionMinor) { 
        
        StartShipmentRequest.initialize(this, trackingId, startTimestamp, commissioningTime, shipmentProfileId, nonce, macAddress, firmwareVersionMajor, firmwareVersionMinor);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, trackingId, startTimestamp, commissioningTime, shipmentProfileId, nonce, macAddress, firmwareVersionMajor, firmwareVersionMinor) { 
        obj['tracking_id'] = trackingId;
        obj['start_timestamp'] = startTimestamp;
        obj['commissioning_time'] = commissioningTime;
        obj['shipment_profile_id'] = shipmentProfileId;
        obj['nonce'] = nonce;
        obj['mac_address'] = macAddress;
        obj['firmware_version_major'] = firmwareVersionMajor;
        obj['firmware_version_minor'] = firmwareVersionMinor;
    }

    /**
     * Constructs a <code>StartShipmentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StartShipmentRequest} obj Optional instance to populate.
     * @return {module:model/StartShipmentRequest} The populated <code>StartShipmentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StartShipmentRequest();

            if (data.hasOwnProperty('tracking_id')) {
                obj['tracking_id'] = ApiClient.convertToType(data['tracking_id'], 'String');
            }
            if (data.hasOwnProperty('start_timestamp')) {
                obj['start_timestamp'] = ApiClient.convertToType(data['start_timestamp'], 'String');
            }
            if (data.hasOwnProperty('commissioning_time')) {
                obj['commissioning_time'] = ApiClient.convertToType(data['commissioning_time'], 'String');
            }
            if (data.hasOwnProperty('shipment_profile_id')) {
                obj['shipment_profile_id'] = ApiClient.convertToType(data['shipment_profile_id'], 'String');
            }
            if (data.hasOwnProperty('nonce')) {
                obj['nonce'] = ApiClient.convertToType(data['nonce'], 'String');
            }
            if (data.hasOwnProperty('mac_address')) {
                obj['mac_address'] = ApiClient.convertToType(data['mac_address'], 'String');
            }
            if (data.hasOwnProperty('firmware_version_major')) {
                obj['firmware_version_major'] = ApiClient.convertToType(data['firmware_version_major'], 'Number');
            }
            if (data.hasOwnProperty('firmware_version_minor')) {
                obj['firmware_version_minor'] = ApiClient.convertToType(data['firmware_version_minor'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} tracking_id
 */
StartShipmentRequest.prototype['tracking_id'] = undefined;

/**
 * @member {String} start_timestamp
 */
StartShipmentRequest.prototype['start_timestamp'] = undefined;

/**
 * @member {String} commissioning_time
 */
StartShipmentRequest.prototype['commissioning_time'] = undefined;

/**
 * @member {String} shipment_profile_id
 */
StartShipmentRequest.prototype['shipment_profile_id'] = undefined;

/**
 * @member {String} nonce
 */
StartShipmentRequest.prototype['nonce'] = undefined;

/**
 * @member {String} mac_address
 */
StartShipmentRequest.prototype['mac_address'] = undefined;

/**
 * @member {Number} firmware_version_major
 */
StartShipmentRequest.prototype['firmware_version_major'] = undefined;

/**
 * @member {Number} firmware_version_minor
 */
StartShipmentRequest.prototype['firmware_version_minor'] = undefined;






export default StartShipmentRequest;

