/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Language from './Language';

/**
 * The UpdateownUserRequest model module.
 * @module model/UpdateownUserRequest
 * @version 4.3.2
 */
class UpdateownUserRequest {
    /**
     * Constructs a new <code>UpdateownUserRequest</code>.
     * @alias module:model/UpdateownUserRequest
     * @param language {module:model/Language} 
     */
    constructor(language) { 
        
        UpdateownUserRequest.initialize(this, language);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, language) { 
        obj['language'] = language;
    }

    /**
     * Constructs a <code>UpdateownUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateownUserRequest} obj Optional instance to populate.
     * @return {module:model/UpdateownUserRequest} The populated <code>UpdateownUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateownUserRequest();

            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('language')) {
                obj['language'] = Language.constructFromObject(data['language']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} first_name
 */
UpdateownUserRequest.prototype['first_name'] = undefined;

/**
 * @member {String} last_name
 */
UpdateownUserRequest.prototype['last_name'] = undefined;

/**
 * @member {String} phone
 */
UpdateownUserRequest.prototype['phone'] = undefined;

/**
 * @member {module:model/Language} language
 */
UpdateownUserRequest.prototype['language'] = undefined;






export default UpdateownUserRequest;

