/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ModumMoDsenseApi);
  }
}(this, function(expect, ModumMoDsenseApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ModumMoDsenseApi.GatewayInstallation();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GatewayInstallation', function() {
    it('should create an instance of GatewayInstallation', function() {
      // uncomment below and update the code to test GatewayInstallation
      //var instane = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be.a(ModumMoDsenseApi.GatewayInstallation);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be();
    });

    it('should have the property clientId (base name: "client_id")', function() {
      // uncomment below and update the code to test the property clientId
      //var instance = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be();
    });

    it('should have the property deletedAt (base name: "deleted_at")', function() {
      // uncomment below and update the code to test the property deletedAt
      //var instance = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be();
    });

    it('should have the property lastSeen (base name: "last_seen")', function() {
      // uncomment below and update the code to test the property lastSeen
      //var instance = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be();
    });

    it('should have the property companyId (base name: "company_id")', function() {
      // uncomment below and update the code to test the property companyId
      //var instance = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "company_name")', function() {
      // uncomment below and update the code to test the property companyName
      //var instance = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be();
    });

    it('should have the property heartbeatData (base name: "heartbeat_data")', function() {
      // uncomment below and update the code to test the property heartbeatData
      //var instance = new ModumMoDsenseApi.GatewayInstallation();
      //expect(instance).to.be();
    });

  });

}));
