/**
 * Modum MODsense API
 * Allows you to interact with the modum system
 *
 * The version of the OpenAPI document: 4.3.2
 * Contact: support@modum.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ModumMoDsenseApi);
  }
}(this, function(expect, ModumMoDsenseApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ModumMoDsenseApi.InlineResponse2001();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse2001', function() {
    it('should create an instance of InlineResponse2001', function() {
      // uncomment below and update the code to test InlineResponse2001
      //var instane = new ModumMoDsenseApi.InlineResponse2001();
      //expect(instance).to.be.a(ModumMoDsenseApi.InlineResponse2001);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ModumMoDsenseApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new ModumMoDsenseApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property shipmentId (base name: "shipment_id")', function() {
      // uncomment below and update the code to test the property shipmentId
      //var instance = new ModumMoDsenseApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property trackingId (base name: "tracking_id")', function() {
      // uncomment below and update the code to test the property trackingId
      //var instance = new ModumMoDsenseApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property sendEmail (base name: "send_email")', function() {
      // uncomment below and update the code to test the property sendEmail
      //var instance = new ModumMoDsenseApi.InlineResponse2001();
      //expect(instance).to.be();
    });

    it('should have the property sendSms (base name: "send_sms")', function() {
      // uncomment below and update the code to test the property sendSms
      //var instance = new ModumMoDsenseApi.InlineResponse2001();
      //expect(instance).to.be();
    });

  });

}));
